line-length = 88
target-version = "py312"

[lint]
select = ["ALL"]
fixable = ["ALL"]
ignore = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D107",
    "D203",
    "D213",
    "PTH123",
    "PLR0911",
    "PLR0913",
    "PLR0915",
    "T201",
    "ANN201",
    "BLE001",
    "COM812",
]

[lint.per-file-ignores]
"examples/*" = ["INP001", "S105", "S106"]
"tests/*" = ["S101", "N803", "ARG", "INP001", "PLR2004", "EM"]

[format]
quote-style = "double"
