# ruff: noqa: N803
from typing import Any, Protocol


class S3Client(Protocol):
    def put_object(
        self, *, Bucket: str, Key: str, Body: bytes, IfNoneMatch: str = ...
    ) -> dict[str, Any]: ...

    def get_object(self, *, Bucket: str, Key: str) -> dict[str, Any]: ...

    def delete_object(self, *, Bucket: str, Key: str) -> dict[str, Any]: ...

    def list_objects_v2(
        self, *, Bucket: str, Prefix: str = ..., ContinuationToken: str = ...
    ) -> dict[str, Any]: ...
