# ruff: noqa: N803
from collections.abc import Iterator
from typing import Any, Protocol


class S3Paginator(Protocol):
    def paginate(
        self, *, Bucket: str, Prefix: str = ...
    ) -> Iterator[dict[str, Any]]: ...


class S3Client(Protocol):
    def put_object(
        self, *, Bucket: str, Key: str, Body: bytes, IfNoneMatch: str = ...
    ) -> dict[str, Any]: ...

    def get_object(self, *, Bucket: str, Key: str) -> dict[str, Any]: ...

    def delete_object(self, *, Bucket: str, Key: str) -> dict[str, Any]: ...

    def get_paginator(self, operation_name: str, /) -> S3Paginator: ...
